src/Entity/ArticlesPress.php
<?php

namespace App\Entity;

use App\Repository\ArticlesPressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=ArticlesPressRepository::class)
 */
class ArticlesPress
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @Gedmo\Slug(fields={"titre"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $featured_image;

    
    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="articlesPresses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity=PressImages::class, mappedBy="press", orphanRemoval=true, cascade={"persist"})
     */
    private $images;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $categorie;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function  getTitre(): ?string
    {
        return $this->titre;
    }
    
    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }


    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }


    public function getFeaturedImage(): ?string
    {
        return $this->featured_image;
    }

    public function setFeaturedImage(string $featured_image): self
    {
        $this->featured_image = $featured_image;

        return $this;
    }



    public function getUsers(): ?Users
    {
        return $this->users;
    }

    public function setUsers(?Users $users): self
    {
        $this->users = $users;

        return $this;
    }

    public function __toString()
    {
        return $this->getTitre();
        return $this->getCreatedAt();
        return $this->getCategorie();
    }

    /**
     * @return Collection|PressImages[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(PressImages $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setPress($this);
        }

        return $this;
    }

    public function removeImage(PressImages $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getPress() === $this) {
                $image->setPress(null);
            }
        }

        return $this;
    }


    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(?string $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

}

src/Controller/ActualiteController.php
<?php

namespace App\Controller;

use App\Entity\ArticlesBoutique;
use App\Entity\ArticlesPress;
use App\Repository\ArticlesPressRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ActualiteController extends AbstractController
{
    /**
     * @Route("/actualite", name="actualite")
     */
    public function index()
    {
        return $this->render('actualite/index.html.twig', [
            'controller_name' => 'ActualiteController',
        ]);
    }

    /**
     * @Route("/actualite/bureau", name="bureau1")
     */
    public function bureau1()
    {

        $articles = $this->getDoctrine()->getRepository(ArticlesPress::class)->findBy(["categorie"=>"bureau"],['created_at' => 'desc']);
        return $this->render('actualite/bureau.html.twig', [
            'articles' => $articles,
        ]);
    }

        /**
     * @Route("/actualite/boutique", name="boutique1")
     */
    public function boutique()
    {
        $articles2 = $this->getDoctrine()->getRepository(ArticlesPress::class)->findBy(["categorie"=>"boutique"],['created_at' => 'desc']);
        return $this->render('actualite/boutique.html.twig', [
            'articles2' => $articles2,
        ]);
    }

        /**
     * @Route("/actualite/sport", name="sport1")
     */
    public function sport()
    {
        $articles3 = $this->getDoctrine()->getRepository(ArticlesPress::class)->findBy(["categorie"=>"sport"],['created_at' => 'desc']);
        return $this->render('actualite/sport.html.twig', [
            'articles3' => $articles3,
        ]);
    }
}

templates/actualite/boutique.html.twig
{% extends 'base.html.twig' %}

{% block title %}L'actu Boutique{% endblock %}

{% block body %}
   <div class="container-fluid">
      <div class="row"style="
                    background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),  url(https://i.ibb.co/Kx37GqB/Whats-App-Image-2022-10-27-21-09-07.jpg) no-repeat center bottom fixed; 
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover; ">
        <div class="col-md-12 text-white text-center p-4">
            <h2 class="text-uppercase p-1" style="font-size: 2.5rem; font-weight: 800;">Actualité Boutique</h2>
        </div>
    </div>
  </div>

  <div class="container-fluid">
  

      <div class="d-flex">
      
              <a class="nav-link disabled"
          ><span style="color: #000;!important;">Actualités</span></a>

                   <a class="nav-link disabled ps-0 pe-0"
          >/</a>
                  <a class="nav-link active" aria-current="page" href="{{ path('bureau1') }}">Bureau</a>
<a class="nav-link disabled ps-0 pe-0"
          >/</a>

        
        <a class="nav-link disabled" aria-current="page" href="{{ path('boutique1') }}"><span style="color: #000;!important;">Boutique</span></a>

           <a class="nav-link disabled ps-0 pe-0"
          >/</a>
        <a class="nav-link active" aria-current="page" href="{{ path('sport1') }}">Sport</a>

      </div>  
  </div>

    <div class="container-fluid" style="background-color: rgba(53, 118, 183, 0.2)">


  <div class="container">
    <div class="row p-5">
    





<!-- Section: Blog v.1 -->



 {% for articles2 in articles2 %} <!-- Grid row -->
 

 <div class="card mt-2 mb-2">
  <div class="row d-flex">

    <!-- Grid column -->
    <div class=" p-1 col-md-4 flex-row d-flex justify-content-center" >

        
          {% for image in articles2.images %}
           <div style="height: 200px; width: 100%; background: url('{{ asset('/uploads/'~image.name) }}') no-repeat center center ;
            -webkit-background-size: contain;
  -moz-background-size: contain;
  -o-background-size: contain;
  background-size: contain;">
  <div class="text-center ">
                
                  

  </div>
          {% endfor %}

          

    </div>
    </div>

    <!-- Grid column -->

    <!-- Grid column -->
    <div class="d-flex flex-column col-md-8 justify-content-between text-start p-4">

      <!-- Category -->

      <!-- Post title -->
      <h3 class="text-uppercase display-6 mb-3" style="font-size: 1.5rem; color: #3576b7;font-weight: 800;">  {{ articles2.titre }}</h3>
      <!-- Excerpt -->
      <div class="h4"  style="font-size: 1.125rem; color:black;font-weight: 800; overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{articles2.contenu|striptags|raw}}</div>
      <!-- Post data -->
      <p style="font-size: 1rem; color:black;font-weight: 800;"><a href="https://www.facebook.com/ajatriathlon/">Facebook</a> {{ articles2.createdAt|date }}</p>
      <!-- Read more button -->

      <button style="background-color: rgb(53, 118, 183); font-size: 1.125rem; color:white;font-weight: 800; " type="button" class="btn text-center" data-mdb-toggle="modal" data-mdb-target="#test{{articles2.id}}">
        Voir l'article !
      </button>

      <!-- Modal -->
      <div class="modal fade" id="test{{articles2.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header d-flex flex-column">
               {% for image in articles2.images %}

                <img class="image-fluid" src="{{ asset('/uploads/'~image.name) }}" alt="" width="100%" height="auto">

              {% endfor %}
            </div>
            <h5 class="modal-title text-uppercase text-center" style="font-size: 1.5rem; color: #3576b7;font-weight: 800;" id="exampleModalLabel">{{ articles2.titre }}</h5>
            <div class="modal-body" style="font-size: 1.125rem; color:black;">{{ articles2.contenu|raw }}</div>
                  <p ><a href="https://www.facebook.com/ajatriathlon/">Facebook</a> {{ articles2.createdAt|date }}</p>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

    </div>
    <!-- Grid column -->

  </div>
  <!-- Grid row -->


</div>

{% endfor %}
</div>
</div>
</div>
</div>
{% endblock %}

templates/actualite/bureau.html.twig
{% extends 'base.html.twig' %}

{% block title %}L'actu Bureau{% endblock %}

{% block body %}

  <!--Main layout-->

    <div class="container-fluid">
      <div class="row"style="
                    background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),  url(https://i.ibb.co/Kx37GqB/Whats-App-Image-2022-10-27-21-09-07.jpg) no-repeat center bottom fixed; 
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover; ">
        <div class="col-md-12 text-white text-center p-4">
            <h2 class="text-uppercase p-1" style="font-size: 2.5rem; font-weight: 800;">Actualité Bureau</h2>
        </div>
    </div>
  </div>
  
  <div class="container-fluid d-flex">
    
              <a class="nav-link disabled"
          ><span style="color: #000;!important;">Actualités</span></a>
                   <a class="nav-link disabled ps-0 pe-0"
          >/</a>
          <a class="nav-link disabled" aria-current="page" href="{{ path('bureau1') }}"><span style="color: #000;!important;">Bureau</span></a>
         <a class="nav-link disabled ps-0 pe-0"
          >/</a>
        <a class="nav-link active" aria-current="page" href="{{ path('boutique1') }}">Boutique</a>
         <a class="nav-link disabled ps-0 pe-0"
          >/</a>   
        <a class="nav-link active" aria-current="page" href="{{ path('sport1') }}">Sport</a>
      </div>

    <div class="container-fluid" style="background-color: rgba(53, 118, 183, 0.2)">
  <div class="container">
    <div class="row p-5">






<!-- Section: Blog v.1 -->



 {% for articles in articles %} <!-- Grid row -->
 

 <div class="card mt-2 mb-2">
  <div class="row d-flex">

    <!-- Grid column -->
    <div class=" p-1 col-md-4 flex-row d-flex justify-content-center" >

        
          {% for image in articles.images %}
           <div style="height: 200px; width: 100%; background: url('{{ asset('/uploads/'~image.name) }}') no-repeat center center ;
            -webkit-background-size: contain;
  -moz-background-size: contain;
  -o-background-size: contain;
  background-size: contain;">
  <div class="text-center ">
                
                  

  </div>
          {% endfor %}

          

    </div>
    </div>

    <!-- Grid column -->

    <!-- Grid column -->
    <div class="d-flex flex-column col-md-8 justify-content-between text-start p-4">

      <!-- Category -->

      <!-- Post title -->
      <h3 class="text-uppercase mb-3" style="font-size: 1.5rem; color: #3576b7;font-weight: 800;">  {{ articles.titre }}</h3>
      <!-- Excerpt -->
      <p style="font-size: 1.125rem; color:black;font-weight: 800; overflow: hidden!important; white-space: nowrap!important; text-overflow: ellipsis!important;">{{ articles.contenu|striptags|raw }}</p>
      <!-- Post data -->
      <p style="font-size: 1rem; color:black;font-weight: 800;"><a href="https://www.facebook.com/ajatriathlon/">Facebook</a> {{ articles.createdAt|date }}</p>
      <!-- Read more button -->

      <button style="background-color: rgb(53, 118, 183); font-size: 1.125rem; color:white;font-weight: 800; " type="button" class="btn text-center" data-mdb-toggle="modal" data-mdb-target="#test{{articles.id}}">
        Voir l'article !
      </button>

      <!-- Modal -->
      <div class="modal fade" id="test{{articles.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header d-flex flex-column">
               {% for image in articles.images %}

                <img class="image-fluid" src="{{ asset('/uploads/'~image.name) }}" alt="" width="100%" height="auto">

              {% endfor %}
            </div>
            <h5 class="modal-title text-uppercase text-center" style="font-size: 1.5rem; color: #3576b7;font-weight: 800;" id="exampleModalLabel">{{ articles.titre }}</h5>
            <div class="modal-body" style="font-size: 1.125rem; color:black;">{{ articles.contenu|raw }}</div>
                  <p class="text-center"><a href="https://www.facebook.com/ajatriathlon/">Facebook</a> {{ articles.createdAt|date }}</p>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

    </div>
    <!-- Grid column -->

  </div>
  <!-- Grid row -->


</div>

{% endfor %}
</div>
</div>
</div>
</div>
{% endblock %}

templates/actualite/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ActualiteController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/laragon/www/AJA-TRI/src/Controller/ActualiteController.php'|file_link(0) }}">src/Controller/ActualiteController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/laragon/www/AJA-TRI/templates/actualite/index.html.twig'|file_link(0) }}">templates/actualite/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/actualite/sport.html.twig
{% extends 'base.html.twig' %}

{% block title %}L'actu Sport{% endblock %}

{% block body %}
   <div class="container-fluid">
      <div class="row"style="
                    background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),  url(https://i.ibb.co/Kx37GqB/Whats-App-Image-2022-10-27-21-09-07.jpg) no-repeat center bottom fixed; 
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                background-size: cover; ">
        <div class="col-md-12 text-white text-center p-4">
            <h2 class="text-uppercase p-1" style="font-size: 2.5rem; font-weight: 800;">Actualité Sport</h2>
        </div>
    </div>
  </div>
  
  <div class="container-fluid d-flex ">
  
              <a class="nav-link disabled"
          ><span style="color: #000;!important;">Actualités</span></a>
                  
              <a class="nav-link disabled ps-0 pe-0"
          >/</a>
          <a class="nav-link active" aria-current="page" href="{{ path('bureau1') }}">Bureau</a>
         <a class="nav-link disabled ps-0 pe-0"
          >/</a>
        <a class="nav-link active" aria-current="page" href="{{ path('boutique1') }}">Boutique</a>
        <a class="nav-link disabled ps-0 pe-0"
          >/</a>
        <a class="nav-link disabled" aria-current="page" href="{{ path('sport1') }}"><span style="color: #000;!important;">Sport</span></a>
      </div>

    <div class="container-fluid" style="background-color: rgba(53, 118, 183, 0.2)">
  <div class="container">
    <div class="row p-5">






<!-- Section: Blog v.1 -->



 {% for articles3 in articles3 %} <!-- Grid row -->
 

 <div class="card mt-2 mb-2">
  <div class="row d-flex">

    <!-- Grid column -->
    <div class=" p-1 col-md-4 flex-row d-flex justify-content-center" >

        
          {% for image in articles3.images %}
           <div style="height: 200px; width: 100%; background: url('{{ asset('/uploads/'~image.name) }}') no-repeat center center ;
            -webkit-background-size: contain;
  -moz-background-size: contain;
  -o-background-size: contain;
  background-size: contain;">
  <div class="text-center ">
                
                  

  </div>
          {% endfor %}

          

    </div>
    </div>

    <!-- Grid column -->

    <!-- Grid column -->
    <div class="d-flex flex-column col-md-8 justify-content-between text-start p-4">

      <!-- Category -->

      <!-- Post title -->
      <h3 class="text-uppercase display-6 mb-3" style="font-size: 1.5rem; color: #3576b7;font-weight: 800;">  {{ articles3.titre }}</h3>
      <!-- Excerpt -->
      <div class="h4"  style="font-size: 1.125rem; color:black;font-weight: 800; overflow: hidden; white-space: nowrap; text-overflow: ellipsis!important;">{{ articles3.contenu|striptags|raw }}</div>
      <!-- Post data -->
      <p style="font-size: 1rem; color:black;font-weight: 800;"><a href="https://www.facebook.com/ajatriathlon/">Facebook</a> {{ articles3.createdAt|date }}</p>
      <!-- Read more button -->

      <button style="background-color: rgb(53, 118, 183); font-size: 1.125rem; color:white;font-weight: 800;" type="button" class="btn text-center" data-mdb-toggle="modal" data-mdb-target="#test{{articles3.id}}">
        Voir l'article !
      </button>

      <!-- Modal -->
      <div class="modal fade" id="test{{articles3.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header d-flex flex-column">
               {% for image in articles3.images %}

                <img class="image-fluid" src="{{ asset('/uploads/'~image.name) }}" alt="" width="100%" height="auto">

              {% endfor %}
            </div>
            <h5 class="modal-title text-uppercase text-center" style="font-size: 1.5rem; color: #3576b7;font-weight: 800;" id="exampleModalLabel">{{ articles3.titre }}</h5>
            <div class="modal-body" style="font-size: 1.125rem; color:black;">{{ articles3.contenu|raw  }}</div>
                  <p class="text-center"><a href="https://www.facebook.com/ajatriathlon/">Facebook</a> {{ articles3.createdAt|date }}</p>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-mdb-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

    </div>
    <!-- Grid column -->

  </div>
  <!-- Grid row -->


</div>

{% endfor %}
</div>
</div>
</div>
</div>
{% endblock %}